std::string normtype = "2";
std::cout << "Norm of variance of solution = " << solMC.col(1).norm(normtype) << std::endl;
std::cout << "Mean of mean of solution = " << solMC.col(0).mean() << std::endl;
// Export arrays for visualization
VecCreate(PETSC_COMM_WORLD,&rhovar);
VecSetSizes(rhovar,PETSC_DECIDE,N);
VecSetType(rhovar,VECSEQ);
VecCreate(PETSC_COMM_WORLD,&rhomean);
VecSetSizes(rhomean,PETSC_DECIDE,N);
VecSetType(rhomean,VECSEQ);	
VecCreate(PETSC_COMM_WORLD,&Xvec);
VecSetSizes(Xvec,PETSC_DECIDE,N);
VecSetType(Xvec,VECSEQ);
VecCreate(PETSC_COMM_WORLD,&Yvec);
VecSetSizes(Yvec,PETSC_DECIDE,N);
VecSetType(Yvec,VECSEQ);
VecCreate(PETSC_COMM_WORLD,&solvar);
VecSetSizes(solvar,PETSC_DECIDE,N);
VecSetType(solvar,VECSEQ);
VecCreate(PETSC_COMM_WORLD,&solmean);
VecSetSizes(solmean,PETSC_DECIDE,N);
VecSetType(solmean,VECSEQ);
VecCreate(PETSC_COMM_WORLD,&fvec);
VecSetSizes(fvec,PETSC_DECIDE,N);
VecSetType(fvec,VECSEQ);			
for (i = 0;i < N;++i){
	VecSetValues(rhovar,1,&i,&rhoMC(i,1),INSERT_VALUES);
	VecSetValues(rhomean,1,&i,&rhoMC(i,0),INSERT_VALUES);
	VecSetValues(Xvec,1,&i,&X(i),INSERT_VALUES);
	VecSetValues(Yvec,1,&i,&Y(i),INSERT_VALUES);
	VecSetValues(solvar,1,&i,&solMC(i,1),INSERT_VALUES);
	VecSetValues(solmean,1,&i,&solMC(i,0),INSERT_VALUES);
	VecSetValues(fvec,1,&i,&userb[i],INSERT_VALUES);		
}
PetscViewer rhovview,rhomview,solvview,solmview,fview,Xview,Yview;
PetscViewerCreate(PETSC_COMM_WORLD,&rhomview);
PetscViewerSetType(rhomview,PETSCVIEWERASCII);
PetscViewerASCIIOpen(PETSC_COMM_WORLD,"rho_mean.dat",&rhomview);
PetscViewerCreate(PETSC_COMM_WORLD,&rhovview);
PetscViewerSetType(rhovview,PETSCVIEWERASCII);
PetscViewerASCIIOpen(PETSC_COMM_WORLD,"rho_var.dat",&rhovview);
PetscViewerCreate(PETSC_COMM_WORLD,&Xview);
PetscViewerSetType(Xview,PETSCVIEWERASCII);
PetscViewerASCIIOpen(PETSC_COMM_WORLD,"X.dat",&Xview);
PetscViewerCreate(PETSC_COMM_WORLD,&Yview);
PetscViewerSetType(Yview,PETSCVIEWERASCII);	
PetscViewerASCIIOpen(PETSC_COMM_WORLD,"Y.dat",&Yview);
PetscViewerCreate(PETSC_COMM_WORLD,&solmview);
PetscViewerSetType(solmview,PETSCVIEWERASCII);
PetscViewerASCIIOpen(PETSC_COMM_WORLD,"sol_mean.dat",&solmview);
PetscViewerCreate(PETSC_COMM_WORLD,&solvview);
PetscViewerSetType(solvview,PETSCVIEWERASCII);
PetscViewerASCIIOpen(PETSC_COMM_WORLD,"sol_var.dat",&solvview);	
PetscViewerCreate(PETSC_COMM_WORLD,&fview);
PetscViewerSetType(fview,PETSCVIEWERASCII);	
PetscViewerASCIIOpen(PETSC_COMM_WORLD,"f.dat",&fview);			
VecView(rhovar,rhovview);
VecView(rhomean,rhomview);
VecView(Xvec,Xview);
VecView(Yvec,Yview);
VecView(solvar,solvview);
VecView(solmean,solmview);
VecView(fvec,fview);	
